/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Pablo U
 */
public class Agendas extends javax.swing.JFrame {

    /**
     * Creates new form Agendas
     */
    public Agendas() {
        initComponents();
        Inicio escudo = new Inicio();
        escudo.ajustarImag(escudo0,"src/imagenes/escudo poli.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        escudo0 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Agendar = new javax.swing.JButton();
        Configuracion = new javax.swing.JButton();
        Historial1 = new javax.swing.JButton();
        margenMenu = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        selcDate = new com.toedter.calendar.JDateChooser();
        labelSelFecha = new javax.swing.JLabel();
        selHora = new javax.swing.JComboBox<>();
        viewMap = new javax.swing.JButton();
        labelSelHora = new javax.swing.JLabel();
        selPlace = new javax.swing.JComboBox<>();
        labelSelePlace = new javax.swing.JLabel();
        selRol = new javax.swing.JComboBox<>();
        labelSelLevelEng = new javax.swing.JLabel();
        selLevelEng = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(900, 700));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(escudo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 140, 70));

        titulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 0));
        titulo2.setText("EnglishPoli");
        jPanel2.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 180, 30));

        titulo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo1.setForeground(new java.awt.Color(0, 204, 51));
        titulo1.setText("Interact");
        jPanel2.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, 30));

        Salir.setBackground(new java.awt.Color(0, 204, 54));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel2.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 120, 80));

        Agendar.setBackground(new java.awt.Color(0, 204, 54));
        Agendar.setText("Agendar");
        Agendar.setEnabled(false);
        jPanel2.add(Agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, 80));

        Configuracion.setBackground(new java.awt.Color(0, 204, 54));
        Configuracion.setText("Configuracion");
        jPanel2.add(Configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 120, 80));

        Historial1.setBackground(new java.awt.Color(0, 204, 54));
        Historial1.setText("Historial");
        jPanel2.add(Historial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 80));

        margenMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(margenMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 340));

        labelRol.setText("Rol:");
        jPanel2.add(labelRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        selcDate.setBackground(new java.awt.Color(204, 204, 204));
        selcDate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(selcDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 240, -1));

        labelSelFecha.setText("Selecciona la fecha: ");
        jPanel2.add(labelSelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        selHora.setBackground(new java.awt.Color(204, 204, 204));
        selHora.setForeground(new java.awt.Color(0, 0, 0));
        selHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM" }));
        selHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selHoraActionPerformed(evt);
            }
        });
        jPanel2.add(selHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 130, -1));

        viewMap.setBackground(new java.awt.Color(204, 204, 204));
        viewMap.setForeground(new java.awt.Color(0, 0, 0));
        viewMap.setText("Mapa");
        viewMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMapActionPerformed(evt);
            }
        });
        jPanel2.add(viewMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

        labelSelHora.setText("Selecciona la Hora : ");
        jPanel2.add(labelSelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        selPlace.setBackground(new java.awt.Color(204, 204, 204));
        selPlace.setForeground(new java.awt.Color(0, 0, 0));
        selPlace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "BLOQUE ADMINISTRATIVO", "ZONA DE ESTUDIOS LOS NARANJOS", "ZONA DE ESTUDIOS LOS ALMENDROS", "BLOQUE P40", "PORTERIA METRO", " " }));
        selPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selPlaceActionPerformed(evt);
            }
        });
        jPanel2.add(selPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 230, -1));

        labelSelePlace.setText("Selecciona lugar de encuentro: ");
        jPanel2.add(labelSelePlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        selRol.setBackground(new java.awt.Color(204, 204, 204));
        selRol.setForeground(new java.awt.Color(0, 0, 0));
        selRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asesor", "Aprendiz" }));
        jPanel2.add(selRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        labelSelLevelEng.setText("Nivel Ingles: ");
        jPanel2.add(labelSelLevelEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        selLevelEng.setBackground(new java.awt.Color(204, 204, 204));
        selLevelEng.setForeground(new java.awt.Color(0, 0, 0));
        selLevelEng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingles 1", "Ingles 2", "Ingles 3", " ", " " }));
        selLevelEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selLevelEngActionPerformed(evt);
            }
        });
        jPanel2.add(selLevelEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void viewMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMapActionPerformed
        mapa mapaPoli = new mapa();
        mapaPoli.setVisible(true);
    }//GEN-LAST:event_viewMapActionPerformed

    private void selHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selHoraActionPerformed

    private void selPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selPlaceActionPerformed

    private void selLevelEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selLevelEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selLevelEngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agendar;
    private javax.swing.JButton Configuracion;
    private javax.swing.JButton Historial1;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel escudo0;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelSelFecha;
    private javax.swing.JLabel labelSelHora;
    private javax.swing.JLabel labelSelLevelEng;
    private javax.swing.JLabel labelSelePlace;
    private javax.swing.JLabel margenMenu;
    private javax.swing.JComboBox<String> selHora;
    private javax.swing.JComboBox<String> selLevelEng;
    private javax.swing.JComboBox<String> selPlace;
    private javax.swing.JComboBox<String> selRol;
    private com.toedter.calendar.JDateChooser selcDate;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JButton viewMap;
    // End of variables declaration//GEN-END:variables
}
