/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import inenpoli.Cita;
import inenpoli.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo U
 */
public class Agendas extends javax.swing.JFrame {

    /**
     * Creates new form Agendas
     */
    Usuario usuarioUso;
    
    DefaultTableModel model;
    public Agendas(Usuario usuario) {
        initComponents();
        usuarioUso = new Usuario();
        usuarioUso = usuario;
        //Inicio escudo = new Inicio();
        //escudo.ajustarImag(escudo0,"src/imagenes/escudo poli.png");
        textNombreBanner.setText(usuario.getName());
        textLastNameBanner.setText(usuarioUso.getLastName());
        model = new DefaultTableModel();
        model.addColumn("Numero Agenda");
        model.addColumn("Fecha ");
        model.addColumn("Hora");
        model.addColumn("Lugar");
        this.tablaAsesorias.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        Agendar = new javax.swing.JButton();
        Configuracion = new javax.swing.JButton();
        Historial1 = new javax.swing.JButton();
        margenMenu = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        titulo = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        viewUsurio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNombreBanner = new javax.swing.JLabel();
        textLastNameBanner = new javax.swing.JLabel();
        botones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Escudo = new javax.swing.JPanel();
        Fondo = new javax.swing.JPanel();
        seleccion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelSelFecha = new javax.swing.JLabel();
        selcDate = new com.toedter.calendar.JDateChooser();
        labelRol = new javax.swing.JLabel();
        selHora = new javax.swing.JComboBox<>();
        viewMap = new javax.swing.JButton();
        labelSelHora = new javax.swing.JLabel();
        selPlace = new javax.swing.JComboBox<>();
        labelSelePlace = new javax.swing.JLabel();
        selRol = new javax.swing.JComboBox<>();
        labelSelLevelEng = new javax.swing.JLabel();
        selLevelEng = new javax.swing.JComboBox<>();
        viewMap1 = new javax.swing.JButton();
        labelSTema = new javax.swing.JLabel();
        selTema = new javax.swing.JComboBox<>();
        labelObserva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAsesorias = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        verTodasAgend = new javax.swing.JButton();

        Salir.setBackground(new java.awt.Color(0, 204, 54));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Agendar.setBackground(new java.awt.Color(0, 204, 54));
        Agendar.setText("Agendar");
        Agendar.setEnabled(false);

        Configuracion.setBackground(new java.awt.Color(0, 204, 54));
        Configuracion.setText("Configuracion");

        Historial1.setBackground(new java.awt.Color(0, 204, 54));
        Historial1.setText("Historial");

        margenMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(margenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Historial1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(Agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(160, 160, 160)
                            .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(Historial1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(margenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InteractEnglishPoli");
        setPreferredSize(new java.awt.Dimension(1100, 700));

        menu.setBackground(new java.awt.Color(25, 104, 68));
        menu.setPreferredSize(new java.awt.Dimension(245, 230));
        menu.setLayout(new javax.swing.BoxLayout(menu, javax.swing.BoxLayout.Y_AXIS));

        titulo.setOpaque(false);
        titulo.setPreferredSize(new java.awt.Dimension(189, 35));

        titulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 0));
        titulo2.setText("EnglishPoli");

        titulo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo1.setForeground(new java.awt.Color(0, 204, 51));
        titulo1.setText("Interact");

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menu.add(titulo);

        viewUsurio.setBackground(new java.awt.Color(255, 255, 255));
        viewUsurio.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102)));
        viewUsurio.setMaximumSize(new java.awt.Dimension(189, 60));
        viewUsurio.setPreferredSize(new java.awt.Dimension(189, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N

        textNombreBanner.setForeground(new java.awt.Color(0, 0, 0));
        textNombreBanner.setText("Usuario #001");
        textNombreBanner.setMaximumSize(new java.awt.Dimension(68, 25));
        textNombreBanner.setMinimumSize(new java.awt.Dimension(68, 25));

        textLastNameBanner.setText("jLabel2");

        javax.swing.GroupLayout viewUsurioLayout = new javax.swing.GroupLayout(viewUsurio);
        viewUsurio.setLayout(viewUsurioLayout);
        viewUsurioLayout.setHorizontalGroup(
            viewUsurioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewUsurioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewUsurioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNombreBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLastNameBanner))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        viewUsurioLayout.setVerticalGroup(
            viewUsurioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewUsurioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(viewUsurioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(viewUsurioLayout.createSequentialGroup()
                        .addComponent(textNombreBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textLastNameBanner)))
                .addGap(50, 50, 50))
        );

        menu.add(viewUsurio);

        botones.setBackground(new java.awt.Color(25, 104, 68));
        botones.setForeground(new java.awt.Color(0, 0, 0));
        botones.setLayout(new java.awt.GridLayout(0, 1));

        jButton1.setBackground(new java.awt.Color(1, 58, 6));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agendar");
        jButton1.setPreferredSize(new java.awt.Dimension(75, 30));
        botones.add(jButton1);

        jButton4.setBackground(new java.awt.Color(1, 58, 6));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Historial");
        jButton4.setPreferredSize(new java.awt.Dimension(75, 30));
        botones.add(jButton4);

        jButton2.setBackground(new java.awt.Color(1, 58, 6));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Configurar");
        jButton2.setPreferredSize(new java.awt.Dimension(75, 30));
        botones.add(jButton2);

        jButton3.setBackground(new java.awt.Color(1, 58, 6));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.setPreferredSize(new java.awt.Dimension(75, 30));
        botones.add(jButton3);

        menu.add(botones);

        jPanel4.setBackground(new java.awt.Color(25, 104, 68));
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 150));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        menu.add(jPanel4);

        Escudo.setBackground(new java.awt.Color(25, 104, 68));
        Escudo.setPreferredSize(new java.awt.Dimension(240, 150));

        javax.swing.GroupLayout EscudoLayout = new javax.swing.GroupLayout(Escudo);
        Escudo.setLayout(EscudoLayout);
        EscudoLayout.setHorizontalGroup(
            EscudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );
        EscudoLayout.setVerticalGroup(
            EscudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        menu.add(Escudo);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new java.awt.CardLayout());

        seleccion.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSelFecha.setText("Selecciona la fecha: ");
        jPanel1.add(labelSelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, -1, -1));

        selcDate.setBackground(new java.awt.Color(255, 255, 255));
        selcDate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(selcDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, -1));

        labelRol.setText("Rol:");
        jPanel1.add(labelRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        selHora.setBackground(new java.awt.Color(255, 255, 255));
        selHora.setForeground(new java.awt.Color(0, 0, 0));
        selHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM" }));
        selHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selHoraActionPerformed(evt);
            }
        });
        jPanel1.add(selHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, -1));

        viewMap.setBackground(new java.awt.Color(204, 204, 204));
        viewMap.setForeground(new java.awt.Color(0, 0, 0));
        viewMap.setText("Mapa");
        viewMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMapActionPerformed(evt);
            }
        });
        jPanel1.add(viewMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        labelSelHora.setText("Selecciona la Hora : ");
        jPanel1.add(labelSelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        selPlace.setBackground(new java.awt.Color(255, 255, 255));
        selPlace.setForeground(new java.awt.Color(0, 0, 0));
        selPlace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "BLOQUE ADMINISTRATIVO", "ZONA DE ESTUDIOS LOS NARANJOS", "ZONA DE ESTUDIOS LOS ALMENDROS", "BLOQUE P40", "PORTERIA METRO", " " }));
        selPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selPlaceActionPerformed(evt);
            }
        });
        jPanel1.add(selPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 230, -1));

        labelSelePlace.setText("Selecciona lugar de encuentro: ");
        jPanel1.add(labelSelePlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        selRol.setBackground(new java.awt.Color(255, 255, 255));
        selRol.setForeground(new java.awt.Color(0, 0, 0));
        selRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asesor", "Aprendiz" }));
        jPanel1.add(selRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        labelSelLevelEng.setText("Nivel Ingles: ");
        jPanel1.add(labelSelLevelEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        selLevelEng.setBackground(new java.awt.Color(255, 255, 255));
        selLevelEng.setForeground(new java.awt.Color(0, 0, 0));
        selLevelEng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingles 1", "Ingles 2", "Ingles 3", " ", " " }));
        selLevelEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selLevelEngActionPerformed(evt);
            }
        });
        jPanel1.add(selLevelEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        viewMap1.setBackground(new java.awt.Color(204, 204, 204));
        viewMap1.setForeground(new java.awt.Color(0, 0, 0));
        viewMap1.setText("Reservar");
        viewMap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMap1ActionPerformed(evt);
            }
        });
        jPanel1.add(viewMap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        labelSTema.setText("Tema:");
        jPanel1.add(labelSTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        selTema.setBackground(new java.awt.Color(255, 255, 255));
        selTema.setForeground(new java.awt.Color(0, 0, 0));
        selTema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tema 1", "Tema 2", "Tema 3", "Tema 4", "Tema 5" }));
        jPanel1.add(selTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 90, -1));

        labelObserva.setText("Observaciones:");
        jPanel1.add(labelObserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane1.setViewportView(observaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        seleccion.add(jPanel1);

        tablaAsesorias.setBackground(new java.awt.Color(102, 102, 102));
        tablaAsesorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaAsesorias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(tablaAsesorias);

        jButton5.setText("Ver mis agendas");

        jButton6.setText("Unirme");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Buscar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscar por fecha:");

        verTodasAgend.setText("Ver Todas");
        verTodasAgend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTodasAgendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(408, 408, 408))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(verTodasAgend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(82, 82, 82)
                        .addComponent(jButton6)
                        .addGap(472, 472, 472))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6)
                        .addComponent(jButton7)
                        .addComponent(jLabel3)
                        .addComponent(verTodasAgend))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        seleccion.add(jPanel2);

        Fondo.add(seleccion, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void viewMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMapActionPerformed
        mapa mapaPoli = new mapa();
        mapaPoli.setVisible(true);
    }//GEN-LAST:event_viewMapActionPerformed

    private void selHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selHoraActionPerformed

    private void selPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selPlaceActionPerformed

    private void selLevelEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selLevelEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selLevelEngActionPerformed

    private void viewMap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMap1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void verTodasAgendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTodasAgendActionPerformed
        // TODO add your handling code here:
        this.llenartabla();
    }//GEN-LAST:event_verTodasAgendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Agendas().setVisible(true);
                
                
                
            }
        });
    }
    
    
    public void llenartabla(){
        Cita citas = new Cita();
        Cita vecCitas[];
        vecCitas = citas.cargarAlista();
        String carga[] = new String[4];

        
        for (int i = 0 ; i < vecCitas.length;i++){
            carga[0] = String.valueOf(vecCitas[i].getNumCita());
            carga[1] = vecCitas[i].getDate();
            carga[2] = vecCitas[i].getHour();
            carga[3] = vecCitas[i].getPlace();
            model.addRow(carga);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agendar;
    private javax.swing.JButton Configuracion;
    private javax.swing.JPanel Escudo;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Historial1;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel botones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelObserva;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelSTema;
    private javax.swing.JLabel labelSelFecha;
    private javax.swing.JLabel labelSelHora;
    private javax.swing.JLabel labelSelLevelEng;
    private javax.swing.JLabel labelSelePlace;
    private javax.swing.JLabel margenMenu;
    private javax.swing.JPanel menu;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JComboBox<String> selHora;
    private javax.swing.JComboBox<String> selLevelEng;
    private javax.swing.JComboBox<String> selPlace;
    private javax.swing.JComboBox<String> selRol;
    private javax.swing.JComboBox<String> selTema;
    private com.toedter.calendar.JDateChooser selcDate;
    private javax.swing.JPanel seleccion;
    private javax.swing.JTable tablaAsesorias;
    private javax.swing.JLabel textLastNameBanner;
    private javax.swing.JLabel textNombreBanner;
    private javax.swing.JPanel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JButton verTodasAgend;
    private javax.swing.JButton viewMap;
    private javax.swing.JButton viewMap1;
    private javax.swing.JPanel viewUsurio;
    // End of variables declaration//GEN-END:variables
}
