/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import inenpoli.Usuario;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo U
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    Usuario[] loguinlist;
    
    public Inicio(){}
    
    public Inicio(Usuario[] loguin) {
        initComponents();
        this.loguinlist = loguin;
        ajustarImag(escudo,"src/imagenes/escudo poli - copia.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        loguin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingreso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textPw = new javax.swing.JPasswordField();
        texUsuario = new javax.swing.JTextPane();
        textErrorLog = new javax.swing.JLabel();
        panelEditFondo1 = new javax.swing.JPanel();
        titulo = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        panelEditFondo2 = new javax.swing.JPanel();
        contenedorEscudo = new javax.swing.JPanel();
        escudo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InteractEnglishPoli");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);
        setSize(new java.awt.Dimension(660, 280));

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelFondo.setMaximumSize(new java.awt.Dimension(660, 280));
        panelFondo.setMinimumSize(new java.awt.Dimension(660, 280));
        panelFondo.setPreferredSize(new java.awt.Dimension(650, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loguin.setBackground(new java.awt.Color(255, 255, 255));
        loguin.setForeground(new java.awt.Color(255, 255, 255));
        loguin.setOpaque(false);

        jLabel1.setText("Contraseña:");

        ingreso.setBackground(new java.awt.Color(1, 58, 6));
        ingreso.setForeground(new java.awt.Color(255, 255, 255));
        ingreso.setText("Entrar");
        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuario:");

        textPw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textPw.setMinimumSize(new java.awt.Dimension(64, 30));
        textPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPwActionPerformed(evt);
            }
        });

        texUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textErrorLog.setForeground(new java.awt.Color(255, 255, 255));
        textErrorLog.setText("Usuario No existe");

        javax.swing.GroupLayout loguinLayout = new javax.swing.GroupLayout(loguin);
        loguin.setLayout(loguinLayout);
        loguinLayout.setHorizontalGroup(
            loguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loguinLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(loguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textErrorLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textPw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(texUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loguinLayout.createSequentialGroup()
                        .addGroup(loguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(92, 92, 92))
        );
        loguinLayout.setVerticalGroup(
            loguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loguinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPw, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textErrorLog)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelFondo.add(loguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 340, 170));

        panelEditFondo1.setBackground(new java.awt.Color(1, 58, 6));
        panelEditFondo1.setForeground(new java.awt.Color(0, 0, 0));
        panelEditFondo1.setLayout(null);

        titulo.setOpaque(false);
        titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 0));
        titulo2.setText("EnglishPoli");
        titulo.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 14, 210, 60));

        titulo1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo1.setForeground(new java.awt.Color(0, 204, 51));
        titulo1.setText("Interact");
        titulo.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, -1, 60));

        panelEditFondo1.add(titulo);
        titulo.setBounds(170, -20, 380, 80);

        panelFondo.add(panelEditFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 60));

        panelEditFondo2.setBackground(new java.awt.Color(25, 104, 68));
        panelEditFondo2.setForeground(new java.awt.Color(0, 0, 0));
        panelEditFondo2.setLayout(null);

        contenedorEscudo.setOpaque(false);

        javax.swing.GroupLayout contenedorEscudoLayout = new javax.swing.GroupLayout(contenedorEscudo);
        contenedorEscudo.setLayout(contenedorEscudoLayout);
        contenedorEscudoLayout.setHorizontalGroup(
            contenedorEscudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        contenedorEscudoLayout.setVerticalGroup(
            contenedorEscudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelEditFondo2.add(contenedorEscudo);
        contenedorEscudo.setBounds(0, 0, 190, 100);
        panelEditFondo2.add(escudo);
        escudo.setBounds(70, 100, 190, 100);

        panelFondo.add(panelEditFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        // TODO add your handling code here:
        boolean acceso = false;
        String mensaje = "Error datos"; 
        Usuario usuarioUso = new Usuario();
 
        //mensaje.setText("Usuario invalido");
        //mensaje.setForeground(Color.red);
        for(int i = 0; i < loguinlist.length; i++){
            System.out.println("user vector: "+loguinlist[i].getUser());
            System.out.println(texUsuario.getText());
            if(loguinlist[i].getUser().equalsIgnoreCase(texUsuario.getText())){
                
                if(loguinlist[i].getPw().equals(new String(textPw.getPassword()))){
                    System.out.print("pasa pw");
                    acceso = true;
                    usuarioUso = loguinlist[i];
                }else{
                    mensaje = "Clave invalida";
                    //mensaje.setForeground(Color.red);
                }
            }else{
                
            }
        }
        if(acceso){
            Agendas agendas = new Agendas(usuarioUso);
            agendas.setLocationRelativeTo(null);
            this.dispose();
            agendas.setVisible(true);
        }else{
            textErrorLog.setText(mensaje);
            textErrorLog.setForeground(Color.red);
            textPw.setText("");
        }
      
       
        
    }//GEN-LAST:event_ingresoActionPerformed

    private void textPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPwActionPerformed
    
//private void ajustarImag(JLabel labelEtiqueta, String rutaIm) {
//    ImageIcon imagenOriginal = new ImageIcon(rutaIm);
//
//    // Obtener las dimensiones del JLabel
//    int labelAncho = labelEtiqueta.getWidth()*2;
//    int labelAlto = labelEtiqueta.getHeight()*2;
//
//    // Redimensionar la imagen al tamaño del JLabel con calidad
//    Image imagenRedimensionada = imagenOriginal.getImage().getScaledInstance(labelAncho, labelAlto, Image.SCALE_SMOOTH);
//
//    // Crear un nuevo ImageIcon con la imagen redimensionada
//    ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);
//
//    // Establecer el nuevo icono en el JLabel
//    labelEtiqueta.setIcon(iconoRedimensionado);
//
//    // Forzar al JLabel a repintar
//    labelEtiqueta.repaint();
//
//    System.out.println("Imagen redimensionada y mostrada con éxito.");
//}
//    
    public void ajustarImag(JLabel labelEtiqueta, String rutaIm){
        // se instancia la ruta en el objeto imagen
        ImageIcon imagen = new ImageIcon(rutaIm);
        // se usa icon como una interfaz para almacenar la imagen y poder llevarla al label
        Icon icono = new ImageIcon( imagen.getImage().getScaledInstance(labelEtiqueta.getWidth(), labelEtiqueta.getHeight(),Image.SCALE_AREA_AVERAGING));
        labelEtiqueta.setIcon(icono);
        this.repaint();
        System.out.print("tamaño heigth:" + labelEtiqueta.getHeight() + " width: " + labelEtiqueta.getWidth() + "ruta imagen : " + rutaIm );
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel contenedorEscudo;
    javax.swing.JLabel escudo;
    javax.swing.JButton ingreso;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JPanel loguin;
    javax.swing.JPanel panelEditFondo1;
    javax.swing.JPanel panelEditFondo2;
    javax.swing.JPanel panelFondo;
    javax.swing.JTextPane texUsuario;
    javax.swing.JLabel textErrorLog;
    javax.swing.JPasswordField textPw;
    javax.swing.JPanel titulo;
    javax.swing.JLabel titulo1;
    javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
